branches:
  - master
  - auto
  - try

host:
  distro: fedora/26/atomic
  specs:
    secondary-disk: 10

context: fedora/26/atomic

required: true

env:
  ENABLE_DESTRUCTIVE: "1"

tests:
  - ./.papr.sh

artifacts:
  - tests.log

timeout: 30m

---

inherit: true

host:
  distro: centos/7/atomic/alpha
  specs:
    secondary-disk: 10

context: centos/7/atomic

---

inherit: true

host:
  distro: fedora/26/cloud
  specs:
    secondary-disk: 10

context: fedora/26/cloud

# we install atomic to get the runtime reqs but of course,
# its files will get overwritten by the containerized build
packages:
  - atomic
  - python3-coverage
  - rpm-build
